src/Entity/Grade.php
<?php

namespace App\Entity;

use App\Repository\GradeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;
#[ORM\Entity(repositoryClass: GradeRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Grade
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: UuidType::NAME,unique:true)]
    private Uuid $token;

    #[ORM\Column(length: 60)]
    private ?string $libelle = null;

    #[ORM\Column]
    private ?int $nbre_postes = null;

    #[ORM\Column(type: 'datetime')]
    private \DateTime $dateCreation;

    #[ORM\Column(type: 'datetime')]
    private \DateTime $dateModification;

    #[ORM\ManyToOne(targetEntity: Concours::class, inversedBy: 'grades')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Concours $concours = null;

    /**
     * @var Specialite[]|Collection
     */
    #[ORM\OneToMany(targetEntity: Specialite::class, mappedBy: 'grade', orphanRemoval: true, cascade: ['persist'])]
  
    private Collection $specialites;


    //  /**
    //  * @var Inscription []|Collection
    //  */
    // #[ORM\OneToMany(targetEntity: Inscription::class, mappedBy: 'grade', orphanRemoval: true, cascade: ['persist'])]
    // private Collection $inscrits;

    public function __construct()
    {
        $this->dateCreation = new \DateTime();
        $this->dateModification = new \DateTime();
        $this->specialites = new ArrayCollection();
        // $this->inscrits = new ArrayCollection();

        $this->token= Uuid::v4();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getNbrePostes(): ?int
    {
        return $this->nbre_postes;
    }

    public function setNbrePostes(int $nbre_postes): static
    {
        $this->nbre_postes = $nbre_postes;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): static
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getDateModification(): ?\DateTimeInterface
    {
        return $this->dateModification;
    }

    public function setDateModification(\DateTimeInterface $dateModification): static
    {
        $this->dateModification = $dateModification;

        return $this;
    }
  

    public function getConcours(): ?Concours
    {
        return $this->concours;
    }

    public function setConcours(?Concours $concours): static
    {
        $this->concours = $concours;

        return $this;
    }

    /**
     * @return Collection<int, Specialite>
     */
    public function getSpecialites(): Collection
    {
        return $this->specialites;
    }

    public function addSpecialite(Specialite $specialite): static
    {
        if (!$this->specialites->contains($specialite)) {
            $this->specialites->add($specialite);
            $specialite->setGrade($this);
        }

        return $this;
    }

    public function removeSpecialite(Specialite $specialite): static
    {
        if ($this->specialites->removeElement($specialite)) {
            // set the owning side to null (unless already changed)
            if ($specialite->getGrade() === $this) {
                $specialite->setGrade(null);
            }
        }

        return $this;
    }

    public function getToken(): ?Uuid
    {
        return $this->token;
    }

    public function setToken(Uuid $token): static
    {
        $this->token = $token;

        return $this;
    }

    
    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function setDateModificationValue()
    {
            $this->setDateModification(new \DateTime());
    }

}

src/Entity/Specialite.php
<?php

namespace App\Entity;

use App\Repository\SpecialiteRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
#[ORM\Entity(repositoryClass: SpecialiteRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Specialite
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 60)]
    private ?string $libelle = null;

    #[ORM\Column(type: 'datetime')]
    private \DateTime $dateCreation;

    #[ORM\Column(type: 'datetime')]
    private \DateTime $dateModification;

    // #[ORM\ManyToMany(targetEntity: Gouvernorat::class, mappedBy: 'specialites')]
    // #[ORM\JoinTable(name: 'gouvernorats_specialites')]
    // #[ORM\JoinColumn(name:"gouvernorat_id", referencedColumnName:"codeGouv")]
    // private Collection $gouvts;

    #[ORM\ManyToMany(targetEntity: Gouvernorat::class, inversedBy: 'specialites')]
    #[ORM\JoinTable(name: 'gouvernorats_specialites')]
    #[Assert\Count(min: 1, max : 24)]
    private Collection $gouvernorats;


    #[ORM\ManyToOne(targetEntity: Grade::class, inversedBy: 'specialites')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Grade $grade = null;

 
    /**
     * @var Inscription []|Collection
     */
    #[ORM\OneToMany(targetEntity: Inscription::class, mappedBy: 'specialite', orphanRemoval: true, cascade: ['persist'])]
    private Collection $inscriptions;

    public function __construct()
    {
        $this->dateCreation = new \DateTime();
        $this->dateModification = new \DateTime();
        $this->gouvernorats = new ArrayCollection();
        $this->inscriptions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): static
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getDateModification(): ?\DateTimeInterface
    {
        return $this->dateModification;
    }

    public function setDateModification(\DateTimeInterface $dateModification): static
    {
        $this->dateModification = $dateModification;

        return $this;
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function setDateModificationValue()
    {
            $this->setDateModification(new \DateTime());
    }

    /**
     * @return Collection<int, Gouvernorat>
     */
    public function getGouvernorats(): Collection
    {
        return $this->gouvernorats;
    }

    public function addGouvernorat(Gouvernorat $gouvernorat): static
    {
        if (!$this->gouvernorats->contains($gouvernorat)) {
            $this->gouvernorats->add($gouvernorat);
        }

        return $this;
    }

    public function removeGouvernorat(Gouvernorat $gouvernorat): static
    {
        $this->gouvernorats->removeElement($gouvernorat);

        return $this;
    }

    public function getGrade(): ?Grade
    {
        return $this->grade;
    }

    public function setGrade(?Grade $grade): static
    {
        $this->grade = $grade;

        return $this;
    }

    /**
     * @return Collection<int, Inscription>
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(Inscription $inscription): static
    {
        if (!$this->inscriptions->contains($inscription)) {
            $this->inscriptions->add($inscription);
            $inscription->setSpecialite($this);
        }

        return $this;
    }

    public function removeInscription(Inscription $inscription): static
    {
        if ($this->inscriptions->removeElement($inscription)) {
            // set the owning side to null (unless already changed)
            if ($inscription->getSpecialite() === $this) {
                $inscription->setSpecialite(null);
            }
        }

        return $this;
    }



   
}

src/Form/SpecialiteType.php
<?php

namespace App\Form;

use App\Entity\Gouvernorat;
use App\Entity\Specialite;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Doctrine\ORM\EntityRepository;

class SpecialiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('libelle',TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'placeholder'=>"Libellé specialité",
                ],
                'label' => 'Libellé specialité',
                'label_attr' => ['class' => 'mt-3'],
            ])
            ->add('gouvernorats', EntityType::class, [
                'class' => Gouvernorat::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('c')
                        ->orderBy('c.id', 'ASC');
                    },
                    'attr' => [
                        'class' => 'select2 form-select shadow-none mt-3',
                    ],
                'label' => 'Gouvernorat',
                'label_attr' => ['class' => 'mt-3'],
                'choice_label' => 'libelle_gouv',
                'required'   => true,
                'multiple' => true,
                'expanded' => false,
            ]);
        
               
           
          
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Specialite::class,
        ]);
    }
}

src/Controller/SpecialiteController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Specialite;
use App\Entity\Grade;
use App\Entity\Concours;
use App\Form\SpecialiteType;
use App\Repository\GradeRepository;
use App\Repository\SpecialiteRepository;
use App\Repository\ConcoursRepository;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter as ParamConverter;
#[Route('/admin')]
class SpecialiteController extends AbstractController
{
    #[Route('/concours/{tokenConcours}/grade/{token}/specialites', name: 'specialite_index')]
    public function index(Request $request, EntityManagerInterface $entityManager, #[MapEntity(mapping: ['tokenConcours' => 'token'])] Concours $concours,#[MapEntity(mapping: ['token' => 'token'])]Grade $grade,ConcoursRepository $ConcoursRepository): Response
    {   
        
        $list= $grade->getSpecialites();
   
        return $this->render('grade/index.html.twig', [
            'controller_name' => 'GradeController',
            'list'=>$list,
            'grade'=>$grade,
            'concours'=>$concours
        ]);
    }
  /**
   * Add entity specialité
   */
    #[Route('/concours/{tokenConcours}/grade/{token}/specialite/new', methods: ['GET', 'POST'], name: 'specialite_new')]
    public function new(Request $request, EntityManagerInterface $entityManager, #[MapEntity(mapping: ['tokenConcours' => 'token'])] Concours $concours,#[MapEntity(mapping: ['token' => 'token'])]Grade $grade): Response
    {
        $specialite = new Specialite(); 
        $specialite->setGrade($grade);
       // dd($specialite);
        $form = $this->createForm(SpecialiteType::class, $specialite);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid() ) {
            $entityManager->persist($specialite);
            $entityManager->flush();
            $this->addFlash('success', 'specialité créée avec succès');
            return $this->redirectToRoute('grade_index', ['tokenConcours' => $concours->getToken(), 'token'=>$grade->getToken()]);
        }

        return $this->render('specialite/new.html.twig', [
            'form' => $form->createView(),
            'grade'=>$grade,
        ]);
    }

/**
   * Edit entity specialité
   */
  #[Route('/concours/{tokenConcours}/grade/{tokenGrade}/specialite/{id}/edit', methods: ['GET', 'POST'], name: 'specialite_edit')]
  public function edit(Request $request, EntityManagerInterface $entityManager, #[MapEntity(mapping: ['tokenConcours' => 'token'])] Concours $concours,#[MapEntity(mapping: ['tokenGrade' => 'token'])]Grade $grade,#[MapEntity(mapping: ['id' => 'id'])] Specialite $specialite): Response
  {
      $specialite->setGrade($grade);
   
      $form = $this->createForm(SpecialiteType::class, $specialite);
      $form->handleRequest($request);
      if ($form->isSubmitted() && $form->isValid() ) {
          $entityManager->persist($specialite);
          $entityManager->flush();
          $this->addFlash('success', 'specialité modifiée avec succès');
          return $this->redirectToRoute('grade_show', ['tokenConcours' => $concours->getToken(),'token'=>$grade->getToken()]);
      }

      return $this->render('specialite/edit.html.twig', [
          'form' => $form->createView(),
          'grade'=>$grade,
      ]);
  }

}

templates/specialite/edit.html.twig
{% extends 'layout_admin.html.twig' %}

{% block main %}


        
    <div class="card-body">
            <h4 class="card-title">Modifier Spécialité  </h4>
            
        </div>

            <div class="col-md-12">
              <div class="card">
              {{ form_start(form) }}
                  <div class="card-body">
                    <div class="form-group row">
                       {{ form_label(form.libelle) }}
                      <div class="input-group">
                       {{ form_widget(form.libelle) }}
                      </div>
                    </div>
                     <div class="form-group row">
                       {{ form_label(form.gouvernorats) }}
                      <div class="input-group">
                       {{ form_widget(form.gouvernorats) }}
                      </div>
                    </div> 
                     
                  </div>     
                
                  <div class=" card-body d-flex justify-content-end">
                        <!--begin::Button-->
                        <a href="{{ path('grade_show',{tokenConcours:grade.concours.token,token:grade.token}) }}" class="btn btn-light me-5">Retour à la liste des grades</a>
                        <!--end::Button-->
                        <!--begin::Button-->
                        <button type="submit" class="btn btn-primary">
                            <span class="indicator-label">Enregistrer</span>
                        </button>
                        <!--end::Button-->
                  </div>
                  {{ form_end(form) }}
              </div>
            
            </div>

{% endblock %}

templates/specialite/index.html.twig
{% extends 'layout_admin.html.twig' %}

{% block main %}


    
    <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Liste des grades <a href="{{ path('grade_new',{tokenConcours:concours.token}) }}" class="btn btn-primary me-5" style="float:right"><i class="me-2 mdi mdi-plus-circle"></i>Ajouter grade</a></h5>
                 
                  <div class="table-responsive col-md-12">
                    <table
                      id="zero_config"
                      class="table table-striped table-bordered"
                    >
                      <thead>
                        <tr>
                          <th>Libellé</th>
                          <th>Nombre de postes</th>
                     
                          <th>Date création</th>
                          <th>Date modification</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                      
                      {% for grade in list %}
                        <tr>
                          <td class="field-rtl">  {{grade.libelle}}</td>
                          <td>  {{grade.nbrePostes}}</td>
                          <td>{{grade.dateCreation|date("m/d/Y")}}</td>
                          <td>{{grade.dateModification|date("m/d/Y H/i:s")}}</td>
                         <td><a href="{{path('grade_show',{tokenConcours:concours.token,token:grade.token})}}"><i class="fas fa-eye-dropper" aria-hidden="true"></i>edit<a></td>
                        </tr>
                      {% endfor %}
                       
                         
                     
                       
                      </tbody>
                   
                    </table>
                  </div>
                </div>
              </div>
{% endblock %}

templates/specialite/new.html.twig
{% extends 'layout_admin.html.twig' %}

{% block main %}



        
    <div class="card-body">
            <h4 class="card-title">Ajouter Spécialité  </h4>
            
        </div>

            <div class="col-md-12">
              <div class="card">
              {{ form_start(form) }}
                <div class="card-body">
                    <div class="form-group row">
                       {{ form_label(form.libelle) }}
                      <div class="input-group">
                       {{ form_widget(form.libelle) }}
                      </div>
                    </div>
                     <div class="form-group row">
                       {{ form_label(form.gouvernorats) }}
                      <div class="input-group">
                       {{ form_widget(form.gouvernorats) }}
                      </div>
                    </div> 
                     
                  </div>     
                
                  <div class=" card-body d-flex justify-content-end">
                        <!--begin::Button-->
                        <a href="{{ path('grade_show',{tokenConcours:grade.concours.token,token:grade.token}) }}" class="btn btn-light me-5">Retour </a>
                        <!--end::Button-->
                        <!--begin::Button-->
                        <button type="submit" class="btn btn-primary">
                            <span class="indicator-label">Enregistrer</span>
                        </button>
                        <!--end::Button-->
                  </div>
               
              </div>
              {{ form_end(form) }}
            </div>
 
{% endblock %}

templates/specialite/show.html.twig
{% extends 'layout_admin.html.twig' %}


{% block main %}

            <div class="col-md-8">
              <div class="card">
                
                  <div class="card-body">
                    <h4 class="card-title">Détails du Grade </h4>
                <div class="d-flex justify-content-end" style="margin-top:0">
                            <!--begin::Button-->
                            
                              <a href="{{ path('specialite_new',{tokenConcours:grade.concours.token,tokenGrade:grade.token}) }}" class="btn btn-light me-5"style=>Ajouter une spécialité</a>
                                <a href="" class="btn btn-primary">Modifier</a>
                         
                    </div>
                    <div class="form-group row">
                        Libellé :
                      <div class="input-group">
                       {{ grade.libelle }}
                      </div>
                    </div>
                    <div class="form-group row">
                        Nombre de postes
                        <div class="input-group">
                              {{ grade.nbrePostes }}
                           
                        </div>
                    </div>
                    <div class="form-group row">
                      Spécialités
                      <div class="input-group">
                          
                      </div>
                    </div>
            
                    
               
                    </div>
              </div>
              
            </div>
            
{% endblock %}